#ifndef 4CHANPARSER_GLOBAL_H
#define 4CHANPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FOURCHANPARSER_LIBRARY)
#  define FOURCHANPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FOURCHANPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // 4CHANPARSER_GLOBAL_H
