#ifndef PARSER2CHAN_GLOBAL_H
#define PARSER2CHAN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARSER2CHAN_LIBRARY)
#  define PARSER2CHANSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARSER2CHANSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARSER2CHAN_GLOBAL_H
